### ISSUE TITLE
Outdated Issue

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#11]
The collection of initial recipes will be passed on to the database developers to input recipes into the database.

**Comment by stt19** [comment]
Removing from Sprint 1 because I cannot work on it until Database is up (I believe Eddie is working on it). Additionally, I think we should worry about setting up Users/Food tables first before creating a table for Recipes. I have replaced this task with learning Android Studio so that my workload does not become unbalanced.

**Comment by stt19** [comment]
Removing from Sprint 2 milestone. I had previously spoken with the team about dropping this if I could not finish the current issue I am working on in time. Additionally, it looks like Ed has done this task himself, so I may remove this issue altogether come Sprint 3.

**Comment by stt19** [comment]
This was originally "Enter Recipes into Database - Sherman". It is now outdated as this issue has already been done, so I am closing it.
