### ISSUE TITLE
Familiarize Ourselves with Existing Source Code - Christian

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#21]
Spend an hour or so getting to understand how the existing program works based on its source code.

**Comment by sylchristian** [comment]
I have taken some time to review the two programs that we have in the repo off of which we will base our programs. I think that the recipe assistant that was added more recently is a better program to use as a base, since the structure of the app is more clearly laid out in my opinion. As I study Android development more and more, it becomes clearer to see what is happening in these programs. I can see that the recipe assistant app already has a handful of recipes attached to it complete with XML layouts, which have helped me further understand how all these various files come together to make something that works and looks good. I have had some difficulty trying to compile and run the project however, which I will need to address.
