### ISSUE TITLE
Design and Implement Log-In/Log-Out Process with Emphasis on Libraries/Framework - Zach

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#24]
Create the user authentication mechanism for the app.

**Comment by zsm8** [comment]
Google+ sign in is a secure and supported means of identifying user for your Android applications.

https://developers.google.com/identity/sign-in/android/start

The above link is a guide from Google's developer site. This will be our resource for implementing sign in.

**Comment by zsm8** [comment]
Log in/logout was moved to backlog from Sprint 1 to Sprint 2. The plan is still to utilize Google+ login since Google+ login should be very well supported.

This will lend itself to user profiles with sets of recipes. The plan is to have these available locally until our database is communicating with the app.

**Comment by zsm8** [comment]
Duplicate entry. Going to consolidate issues into different issue.
