### ISSUE TITLE
Resolve compilation error on search function code

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#56]
After creating the test (which will fail the first time per expectations of Test-Driven Development), implement the search function. A user should be able to enter a string, which represents an ingredient, and subsequently be given a list of recipes that use that ingredient.

**Comment by sylchristian** [comment]
After discussing with the team and opting to implement a standalone search function first and worrying about implementing test driven development at a later date, I have made a small app that compiles and runs on the Android emulator. This app contains an input text box and a button that responds to a tap from the user. After running into issues with the Java code trying to handle text input, I had to revert to a previous version that consists of just one activity. This decision was made in order to have a compilable version of the app living on the remote repository, as that is a priority. I will develop the Java code that handles text input from the user at a later date, as well as look into configuring the continuous integration server with the app.
